project:
  type: website
  output-dir: docs

website:
  title: "BANSI KHACHAR"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Marketing Analytics"
        href: marketing-analytics.qmd
      - text: "Strategic Marketing"
        href: strategic-marketing.qmd
      - text: "Résumé"
        href: resume.qmd


format:
  html:
    theme: [flatly, theme.scss]
    toc: true
    include-in-header: includes/gtm-head.html      # Injects GTM script into <head>
    include-before-body: includes/gtm-body.html    # Injects GTM noscript immediately after <body> opens

